spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thisfinans
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
