version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - thisfinans_data:/var/lib/mysql

volumes:
  thisfinans_data:
